<section class="selected-work" aria-labelledby="selected-work-title">
<p class="eyebrow">Selected work</p><h2 id="selected-work-title">Work you can visit.</h2>
<p class="intro">Websites, creator tools and learning experiences. Explore the work and the tasks each one supports.</p>
<div class="clients">
  {#each [{name:'Maverick X',id:'websites',url:'https://www.maverickx.com/',description:'A public website presenting chemistry across energy, mining and water treatment.'},{name:'Cato Insights Hub',id:'webflow',url:'https://www.catosupply.com/insights',description:'An Insights Hub built with Webflow components, bringing research, reports and newsroom content together.'}] as client}
  <article><a href={`/?film=${client.id}#work`} aria-label={`View ${client.name} website walkthrough`}><img src={`/films/${client.id}/reference.png`} alt={`${client.name} public homepage, captured September 23, 2026`} loading="lazy" width="1440" height="1000" /></a><h3>{client.name}</h3><p>{client.description}</p><div class="links"><a href={`/?film=${client.id}#work`}>Watch the walkthrough →</a><a href={client.url} target="_blank" rel="noreferrer">Visit the live site ↗</a></div></article>
  {/each}
  <article class="product-proof"><video controls playsinline preload="none" poster="/films/dashboard-poster.jpg" aria-label="Webflow Asset Dashboard walkthrough"><source src="/films/dashboard-demo.mp4" type="video/mp4" /><track kind="captions" src="/films/dashboard.vtt" srclang="en" label="English descriptions" /></video><p class="eyebrow">Apps &amp; dashboards</p><h3>Webflow Asset Dashboard</h3><p>A workspace where creators can track review status, explore Marketplace insights, and edit their assets.</p><p class="scope">Recorded with a test portfolio. The editor is opened; no changes are saved.</p><div class="links"><a href="https://github.com/createsomethingtoday/create-something-monorepo/tree/main/packages/webflow-dashboard" target="_blank" rel="noreferrer">Explore the implementation ↗</a></div></article>
  <article class="product-proof"><a href="/?film=education#work" aria-label="Watch the PCN landing-page walkthrough"><img src="/films/pcn-poster.jpg" alt="PCN landing-page product overview" loading="lazy" width="1600" height="1000" /></a><p class="eyebrow">Education / PCN</p><h3>A home for the practice.</h3><p>Private networks for sharing agentic engineering techniques, tools and learning resources.</p><div class="links"><a href="/?film=education#work">Watch the overview →</a><a href="https://private.createsomething.agency" target="_blank" rel="noreferrer">Explore PCN ↗</a></div></article>
</div>
<article class="outerfields-story" aria-labelledby="outerfields-title">
<p class="eyebrow">Outerfields / Prototype &amp; platform development</p>
<h3 id="outerfields-title">From prototype to a funded platform.</h3>
<p>We built the prototype that helped Outerfields secure funding for its first private content network, enabling a $10,000 development budget. Their team later brought development in-house. The lessons from that work informed our own PCN.</p>
<ol class="project-journey" aria-label="From Outerfields to CREATE SOMETHING PCN">
<li><span>01 / Prototype</span><strong>Make the idea tangible.</strong><p>Build the first PCN prototype.</p></li>
<li><span>02 / Funded development</span><strong>$10,000 to develop it.</strong><p>The prototype helped secure funding for the first network.</p></li>
<li><span>03 / In-house development</span><strong>Their team takes it forward.</strong><p>Outerfields later moved development in-house.</p></li>
<li><span>04 / What we learned</span><strong>A foundation for our PCN.</strong><p>Apply those lessons to CREATE SOMETHING’s own platform.</p></li>
</ol>
<div class="links"><a href="/?film=education#work">See our PCN today →</a><a href="https://outerfields.co/" target="_blank" rel="noreferrer">Visit Outerfields today ↗</a></div>
<p class="scope">Our role: the prototype and early development. The current Outerfields site may include later work by its in-house developer.</p>
</article>
<div class="engineering"><div><p class="eyebrow">Engineering contributions</p><h3>We improve the tools we work with.</h3><p>Independent contributions to CTX and OpenAI Codex Security, with accepted changes and release evidence. Our Webflow review-system report documents the work and its limits.</p></div><div class="links"><a href="/field-reports/upstream-contributions">Read the CTX and OpenAI contribution record →</a><a href="/field-reports/template-review">Explore the Webflow review system →</a></div></div>
<p class="scope">Selected projects demonstrate our capabilities. Membership delivery is agreed separately, one workstream at a time.</p>
</section>
<style>
.outerfields-story{margin-top:50px;padding-top:35px;border-top:1px solid var(--color-performance-line)}.project-journey{display:grid;grid-template-columns:repeat(4,1fr);gap:24px;list-style:none;padding:0;margin:32px 0}.project-journey li{border-top:1px solid var(--color-performance-line);padding-top:16px}.project-journey span{display:block;font:11px var(--font-performance-mono);text-transform:uppercase;margin-bottom:14px}.project-journey strong{display:block;font-size:17px;font-weight:500}.project-journey p{font-size:14px;line-height:1.65}@media(max-width:900px){.project-journey{grid-template-columns:repeat(2,1fr)}}@media(max-width:500px){.project-journey{grid-template-columns:1fr}}

.selected-work{padding:80px 7vw;background:var(--color-performance-paper);color:var(--color-performance-ink)}.product-proof video{width:100%;aspect-ratio:1.6;object-fit:contain;background:#f3f3f0;border-radius:10px}.product-proof{border-top:1px solid var(--color-performance-line);padding-top:28px}.eyebrow{color:inherit;font:12px var(--font-performance-mono);text-transform:uppercase;letter-spacing:.06em}h2{font:400 clamp(42px,5vw,70px)/1.1 var(--font-performance-editorial);margin:20px 0}.intro{max-width:700px;line-height:1.65}.clients{display:grid;grid-template-columns:1fr 1fr;gap:40px;margin-top:40px}img{width:100%;height:auto;border-radius:10px;border:1px solid var(--color-performance-line)}h3{font:400 32px/1.2 var(--font-performance-editorial);margin:20px 0 12px}article p,.engineering p{line-height:1.65;max-width:650px}.links{display:flex;flex-wrap:wrap;gap:20px;margin-top:20px}a{color:inherit;text-underline-offset:5px}a:focus-visible{outline:3px solid var(--color-performance-signal);outline-offset:5px}.engineering{border-top:1px solid var(--color-performance-line);margin-top:50px;padding-top:35px;display:grid;grid-template-columns:1.4fr 1fr;gap:40px}.engineering .links{flex-direction:column;justify-content:center}.scope{font-size:13px;margin-top:30px}@media(max-width:700px){.clients,.engineering{grid-template-columns:1fr;gap:30px}.selected-work{padding-block:55px}}
</style>