<script lang="ts">
	import { SEO } from '@create-something/canon';
	let { data, form } = $props();
	const metrics = $derived([
		['Active maps', data.summary.active_maps], ['Archived maps', data.summary.archived_maps],
		['Workspaces', data.summary.workspace_count], ['Versions', data.summary.version_count],
		['Active shares', data.summary.active_shares], ['Prepared handoffs', data.summary.prepared_handoffs]
	]);
</script>

<SEO title="Map Operations | CREATE SOMETHING AGENCY" description="Privacy-safe Map product operations." propertyName="agency" noindex={true} />
<main>
	<header><p>Operator surface</p><h1>Map operations</h1><span>Signed in as {data.operatorEmail}. Share tokens remain absent; prepared handoff payloads are visible only here for explicit Build intake.</span></header>
	<section class="metrics">{#each metrics as metric}<article><span>{metric[0]}</span><strong>{metric[1]}</strong></article>{/each}</section>
	<section class="panel"><h2>Commercial gate</h2><dl><dt>Explicit approval</dt><dd>{data.commercial.approvalRecorded ? 'Recorded' : 'Not recorded'}</dd><dt>Monthly configuration</dt><dd>{data.commercial.monthlyConfigured ? 'Present' : 'Missing'}</dd><dt>Yearly configuration</dt><dd>{data.commercial.yearlyConfigured ? 'Present' : 'Missing'}</dd><dt>Checkout</dt><dd>{data.commercial.checkoutEnabled ? 'Enabled' : 'Fail closed'}</dd></dl></section>
	<section class="panel"><h2>Entitlement lifecycle</h2>{#if data.entitlements.length}<ul>{#each data.entitlements as item}<li><span>{item.entitlement_status.replace('_', ' ')}</span><strong>{item.count}</strong></li>{/each}</ul>{:else}<p>No Map subscription entitlements recorded.</p>{/if}</section>
	<section class="panel"><h2>Prepared Build handoffs</h2>{#if data.preparedHandoffs.length}<div class="handoffs">{#each data.preparedHandoffs as handoff}<article class="handoff"><div><strong>{handoff.mapTitle}</strong><span>Version {handoff.mapVersion} · {handoff.accountId} · {handoff.workspaceAccountId}</span></div><details><summary>Inspect immutable payload</summary><pre>{JSON.stringify(handoff.payload, null, 2)}</pre></details><form method="POST" action="?/acceptHandoff"><input type="hidden" name="handoff_id" value={handoff.id} /><label>Intake note <input name="note" maxlength="240" placeholder="Scope intake verified" /></label><button type="submit">Accept for Build intake</button></form></article>{/each}</div><nav class="pagination" aria-label="Prepared handoff pages">{#if data.handoffPagination.hasPrevious}<a href={`?handoff_page=${data.handoffPagination.page - 1}`}>← Older handoffs</a>{/if}<span>Page {data.handoffPagination.page} · {data.handoffPagination.total} prepared</span>{#if data.handoffPagination.hasNext}<a href={`?handoff_page=${data.handoffPagination.page + 1}`}>Newer handoffs →</a>{/if}</nav>{:else}<p>No prepared Build handoffs on this page.</p>{#if data.handoffPagination.hasPrevious}<a href={`?handoff_page=${data.handoffPagination.page - 1}`}>← Previous handoff page</a>{/if}{/if}{#if form?.message}<p class:success={form.success} class="message">{form.message}</p>{/if}</section>
	<footer><a href="/api/map/health">Credential-free health</a><a href="https://github.com/createsomethingtoday/create-something-monorepo/actions/workflows/agency-map-production-monitor.yml">Synthetic receipts</a><span>Runbook: docs/guides/MAP_PRODUCT_OPERATIONS.md</span></footer>
</main>

<style>
	main { max-width: 1100px; margin: 0 auto; padding: 7rem 1.5rem 5rem; color: #f5f5f5; } header { margin-bottom: 2.5rem; } header p { color: #fbbf24; text-transform: uppercase; letter-spacing: .12em; font-size: .7rem; } h1 { margin: .5rem 0; font-size: clamp(2.5rem, 6vw, 5rem); letter-spacing: -.06em; } header span, .panel p, footer { color: #a1a1aa; }
	.metrics { display: grid; grid-template-columns: repeat(3, 1fr); gap: .7rem; } article, .panel { border: 1px solid #27272a; border-radius: .75rem; padding: 1.2rem; background: #0c0c0d; } article { display: grid; gap: .5rem; } article span { color: #a1a1aa; font-size: .75rem; } article strong { font-size: 2rem; }
	.panel { margin-top: 1rem; } h2 { margin: 0 0 1rem; font-size: 1rem; } dl { display: grid; grid-template-columns: 1fr auto; gap: .6rem; } dt { color: #a1a1aa; } dd { margin: 0; } ul { list-style: none; padding: 0; margin: 0; } li { display: flex; justify-content: space-between; border-top: 1px solid #27272a; padding: .7rem 0; text-transform: capitalize; } .handoffs, .handoff, .handoff form, .handoff label { display: grid; gap: .75rem; } .handoff { grid-column: 1 / -1; } .handoff > div { display: flex; justify-content: space-between; gap: 1rem; } .handoff span, summary, .handoff label { color: #a1a1aa; font-size: .75rem; } details { border-top: 1px solid #27272a; padding-top: .75rem; } summary { cursor: pointer; } pre { overflow: auto; max-height: 24rem; padding: .75rem; background: #09090b; border-radius: .45rem; font-size: .7rem; } .handoff form { grid-template-columns: 1fr auto; align-items: end; } .handoff label input { width: 100%; box-sizing: border-box; margin-top: .35rem; border: 1px solid #3f3f46; border-radius: .4rem; padding: .6rem; background: #09090b; color: #f5f5f5; } button { border: 1px solid #86efac; border-radius: .4rem; padding: .65rem .8rem; background: transparent; color: #86efac; cursor: pointer; } .pagination { display: flex; justify-content: space-between; gap: 1rem; margin-top: 1rem; color: #a1a1aa; font-size: .75rem; } .pagination a { color: #d4d4d8; } .message { color: #fca5a5; } .message.success { color: #86efac; }
	footer { display: flex; flex-wrap: wrap; gap: 1rem; margin-top: 2rem; font-size: .75rem; } footer a { color: #d4d4d8; }
	@media (max-width: 700px) { .metrics { grid-template-columns: 1fr 1fr; } }
</style>
