/**
 * SoundCues - Declarative sound effects for Remotion compositions
 * 
 * Renders multiple Audio components at specified frames with configurable sounds.
 * Sounds are generated by scripts/generate-sounds.ts using Tone.js.
 * 
 * @example
 * <SoundCues cues={[
 *   { frame: 0, sound: 'pop-soft' },
 *   { frame: 30, sound: 'click-mechanical', volume: 0.3 },
 * ]} />
 */
import React from 'react';
import { Audio, Sequence, staticFile } from 'remotion';

/**
 * Available synthesized sounds
 * Generated by: pnpm generate-sounds
 */
export const SOUND_LIBRARY = {
  // Pops & thuds - for element entrances
  'pop-soft': 'sounds/pop-soft.wav',
  'pop-medium': 'sounds/pop-medium.wav',
  'thud-soft': 'sounds/thud-soft.wav',
  
  // Ticks & clicks - for small interactions
  'tick-soft': 'sounds/tick-soft.wav',
  'tick-medium': 'sounds/tick-medium.wav',
  'click-mechanical': 'sounds/click-mechanical.wav',
  'micro-tick': 'sounds/micro-tick.wav',
  
  // Success/approval tones
  'success-chime': 'sounds/success-chime.wav',
  'success-soft': 'sounds/success-soft.wav',
  
  // Dismiss/warning tones
  'dismiss-soft': 'sounds/dismiss-soft.wav',
  'warning-tone': 'sounds/warning-tone.wav',
  
  // Transitions
  'whoosh-soft': 'sounds/whoosh-soft.wav',
  'shimmer': 'sounds/shimmer.wav',
  
  // UI selection
  'select': 'sounds/select.wav',
  'focus': 'sounds/focus.wav',
  
  // Ambient/resolution
  'resolve': 'sounds/resolve.wav',
} as const;

export type SoundName = keyof typeof SOUND_LIBRARY;

export interface SoundCue {
  /** Frame at which to play the sound */
  frame: number;
  /** Sound to play from the library */
  sound: SoundName;
  /** Volume (0-1), defaults to 0.5 */
  volume?: number;
  /** Optional label for debugging */
  label?: string;
}

interface SoundCuesProps {
  /** Array of sound cues to render */
  cues: SoundCue[];
  /** Master volume multiplier (0-1), defaults to 1 */
  masterVolume?: number;
  /** Whether sounds are enabled, defaults to true */
  enabled?: boolean;
}

/**
 * Render sound cues as Remotion Audio sequences
 */
export const SoundCues: React.FC<SoundCuesProps> = ({
  cues,
  masterVolume = 1,
  enabled = true,
}) => {
  if (!enabled) return null;
  
  return (
    <>
      {cues.map((cue, index) => {
        const soundPath = SOUND_LIBRARY[cue.sound];
        const volume = (cue.volume ?? 0.5) * masterVolume;
        
        return (
          <Sequence
            key={`${cue.sound}-${cue.frame}-${index}`}
            from={cue.frame}
            durationInFrames={30} // Most sounds are < 0.5s at 30fps
            name={cue.label || `${cue.sound}@${cue.frame}`}
          >
            <Audio
              src={staticFile(soundPath)}
              volume={volume}
            />
          </Sequence>
        );
      })}
    </>
  );
};

/**
 * Helper to generate cascading sound cues
 * 
 * @example
 * const cues = createCascade({
 *   sound: 'pop-soft',
 *   startFrame: 60,
 *   count: 8,
 *   stagger: 15,
 *   volume: 0.2,
 * });
 */
export function createCascade(options: {
  sound: SoundName;
  startFrame: number;
  count: number;
  stagger: number;
  volume?: number;
  label?: string;
}): SoundCue[] {
  const { sound, startFrame, count, stagger, volume, label } = options;
  
  return Array.from({ length: count }, (_, i) => ({
    frame: startFrame + i * stagger,
    sound,
    volume,
    label: label ? `${label}-${i}` : undefined,
  }));
}

/**
 * Helper to generate rapid-fire sound cues (for counters, etc.)
 */
export function createRapidFire(options: {
  sound: SoundName;
  startFrame: number;
  endFrame: number;
  interval: number;
  volume?: number;
}): SoundCue[] {
  const { sound, startFrame, endFrame, interval, volume } = options;
  const cues: SoundCue[] = [];
  
  for (let frame = startFrame; frame < endFrame; frame += interval) {
    cues.push({ frame, sound, volume });
  }
  
  return cues;
}

export default SoundCues;
