/**
 * Knowledge Graph Server Load
 *
 * Loads graph data from static JSON files generated by build script.
 */

import { readFileSync, existsSync } from 'fs';
import { resolve } from 'path';
import { error } from '@sveltejs/kit';
import type { PageServerLoad } from './$types';
import type { GraphData } from '$lib/graph';

export const load: PageServerLoad = async () => {
	// Navigate from packages/io to monorepo root
	const graphDir = resolve(process.cwd(), '../../.graph');

	const nodesPath = resolve(graphDir, 'nodes.json');
	const edgesPath = resolve(graphDir, 'edges.json');
	const metadataPath = resolve(graphDir, 'metadata.json');

	// Check if graph has been built
	if (!existsSync(nodesPath) || !existsSync(edgesPath) || !existsSync(metadataPath)) {
		throw error(404, {
			message:
				'Knowledge graph not found. Run `pnpm graph:build` to generate graph data.',
		});
	}

	try {
		// Load JSON files
		const nodes = JSON.parse(readFileSync(nodesPath, 'utf-8'));
		const edges = JSON.parse(readFileSync(edgesPath, 'utf-8'));
		const metadata = JSON.parse(readFileSync(metadataPath, 'utf-8'));

		const data: GraphData = {
			nodes,
			edges,
			metadata,
		};

		return { data };
	} catch (err) {
		console.error('Failed to load graph data:', err);
		throw error(500, {
			message: 'Failed to load graph data. Try rebuilding with `pnpm graph:build`.',
		});
	}
};
