# Ground Configuration for CREATE SOMETHING Monorepo
# https://github.com/create-something/ground
#
# This configuration uses a layered approach:
# 1. Framework patterns (SvelteKit, Cloudflare)
# 2. Monorepo conventions (build tools, tests)
# 3. Project-specific exceptions
#
# See .ground/*.yml for detailed pattern documentation.

version: "1"

# ─────────────────────────────────────────────────────────────────────────────
# Pattern Composition
# ─────────────────────────────────────────────────────────────────────────────
# Extends shared pattern files for maintainability and reusability

extends:
  # Framework patterns
  - .ground/sveltekit-patterns.yml    # SvelteKit framework conventions
  - .ground/cloudflare-patterns.yml   # Cloudflare Workers/Pages patterns
  - .ground/monorepo-patterns.yml     # General monorepo patterns
  - .ground/project-specific.yml      # Project-specific exceptions
  
  # Consolidation patterns (from Canon migration audit)
  - .ground/import-health.yml         # Deprecated imports, direct source imports
  - .ground/component-locality.yml    # Components in Canon, not routes
  - .ground/experiment-graduation.yml # Track experiment component usage
  - .ground/duplication.yml           # Duplicate utility detection
  - .ground/dependency-health.yml     # Package.json health checks

# ─────────────────────────────────────────────────────────────────────────────
# Additional Project-Specific Patterns
# ─────────────────────────────────────────────────────────────────────────────
# Patterns unique to this specific project that don't belong in shared configs

ignore:
  functions:
    - getCapabilities      # Required interface method (agent-kit)

# ─────────────────────────────────────────────────────────────────────────────
# Analysis Configuration
# ─────────────────────────────────────────────────────────────────────────────

thresholds:
  duplicate_similarity: 85        # 85% catches violations without false positives
  min_function_lines: 5           # Ignore trivial functions

monorepo:
  enabled: true

report:
  format: markdown
  include_suggestions: true
  group_by: type
  verbose: true

# ─────────────────────────────────────────────────────────────────────────────
# Usage Notes
# ─────────────────────────────────────────────────────────────────────────────
#
# When Ground MCP flags a false positive:
# 1. Determine if it's a framework pattern or project-specific
# 2. Add to appropriate .ground/*.yml file with documentation
# 3. Re-run Ground MCP to verify
#
# Pattern files can be shared across projects using the same stack.
