packages:
  - 'apps/*'
  - 'packages/*'
  - 'packages/agents/*'
  - 'packages/*/clients/*'
  - 'packages/*/dashboard'
  - 'packages/*/extension'
  - 'packages/*/npm'
  - 'packages/*/worker'
  - 'packages/*/workers/*'
  - 'packages/huggingface-spaces/*'
  - 'packages/seeing/*'
  - 'packages/tools/*'
