#!/bin/bash
# Merge Ground MCP pattern files into a single configuration
# Use this if Ground MCP doesn't support the 'extends' directive yet

set -e

GROUND_DIR="$(cd "$(dirname "$0")" && pwd)"
OUTPUT="$GROUND_DIR/../.ground.merged.yml"

echo "# Ground MCP Merged Configuration" > "$OUTPUT"
echo "# Auto-generated by .ground/merge-config.sh" >> "$OUTPUT"
echo "# DO NOT EDIT - Edit pattern files in .ground/ instead" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "version: \"1\"" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Merge all pattern files (skip README and this script)
for file in "$GROUND_DIR"/*.yml; do
  if [ -f "$file" ]; then
    filename=$(basename "$file")
    echo "# ═══════════════════════════════════════════════════════════════════════════" >> "$OUTPUT"
    echo "# Patterns from: $filename" >> "$OUTPUT"
    echo "# ═══════════════════════════════════════════════════════════════════════════" >> "$OUTPUT"
    echo "" >> "$OUTPUT"
    
    # Skip the version line (already added)
    grep -v "^version:" "$file" >> "$OUTPUT"
    echo "" >> "$OUTPUT"
  fi
done

# Add project-specific overrides from main .ground.yml
echo "# ═══════════════════════════════════════════════════════════════════════════" >> "$OUTPUT"
echo "# Project-Specific Overrides (from .ground.yml)" >> "$OUTPUT"
echo "# ═══════════════════════════════════════════════════════════════════════════" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Extract only the project-specific sections (after extends)
awk '/^# Additional Project-Specific Patterns/,0' "$GROUND_DIR/../.ground.yml" \
  | grep -v "^# Additional Project-Specific Patterns" \
  | grep -v "^extends:" \
  >> "$OUTPUT"

echo "✓ Merged configuration written to: $OUTPUT"
echo ""
echo "Usage:"
echo "  ground analyze --config=.ground.merged.yml --directory=."
