[env:m5stack-coreink]
platform = espressif32
board = m5stack-coreink
framework = arduino
monitor_speed = 115200
upload_speed = 460800
lib_deps =
  m5stack/M5Unified
  bblanchon/ArduinoJson@^7.4.2
build_flags =
  -D CORE_DEBUG_LEVEL=0
