name = "guard-performance-lab"
compatibility_date = "2026-06-24"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/cloudflare"

[vars]
ENVIRONMENT = "production"
GUARD_LAB_PROJECT_SIGN_IN_URL = "/sign-in"
GUARD_LAB_SHARED_PLAYER_ID = "56bd44c0-767f-409a-ad0b-2d51778afb2d"

[[d1_databases]]
binding = "GUARD_LAB_DB"
database_name = "guard-performance-lab"
database_id = "ff5bae4e-ff86-46a3-a0bd-f95f5805d953"
migrations_dir = "migrations"
