name = "webflow-app-review-mcp"
main = "index.ts"
compatibility_date = "2026-02-18"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]
account_id = "9645bd52e640b8a4f40a3a55ff1dd75a"

[[durable_objects.bindings]]
name = "MCP_OBJECT"
class_name = "WebflowAppReviewMCP"

[[kv_namespaces]]
binding = "OAUTH_KV"
id = "ef6ba893e47343e0b26b0918775e6b89"
preview_id = "b659942e9bc24630a482ea1a28b4cf80"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["WebflowAppReviewMCP"]

[[d1_databases]]
binding = "TELEMETRY_DB"
database_name = "cs-telemetry"
database_id = "f710641a-0c85-4a7b-bb73-2c16f8d024c3"
