/**
 * Seed Canon References
 *
 * One-time script to populate the canon_references table by discovering
 * connections between experiments and principles.
 *
 * Usage:
 *   pnpm --filter @create-something/ltd exec tsx scripts/seed-canon-references.ts
 *
 * Or via wrangler for production:
 *   wrangler d1 execute create-something-db --remote --file=scripts/seed-canon-references.sql
 *
 * Part of "The Circle Closes" experiment.
 */

// This script generates SQL to insert canon references
// Run it locally and pipe output to a .sql file for wrangler execution

interface ExperimentReference {
	slug: string;
	domain: 'io' | 'space' | 'agency';
	title: string;
	tags: string[];
	principleMatches: string[]; // Principle IDs that match
}

// Known experiments and their principle connections
// This mapping was created by analyzing experiment content against the canon
const EXPERIMENT_REFERENCES: ExperimentReference[] = [
	// .space experiments
	{
		slug: 'motion-ontology',
		domain: 'space',
		title: 'Motion Ontology',
		tags: ['Phenomenology', 'Heidegger', 'Animation'],
		principleMatches: [
			'rams-principle-5', // Unobtrusive - animations that recede (zuhandenheit)
			'rams-principle-10' // As little design as possible - minimal motion
		]
	},
	{
		slug: 'minimal-capture',
		domain: 'space',
		title: 'Minimal Capture',
		tags: ['Hermeneutics', 'Design Canon', 'Propagation'],
		principleMatches: [
			'rams-principle-2', // Useful - every element serves purpose
			'rams-principle-10', // As little design as possible
			'rams-principle-4' // Understandable - self-evident interfaces
		]
	},

	// .io experiments
	{
		slug: 'understanding-graphs',
		domain: 'io',
		title: 'Understanding Graphs',
		tags: ['Hermeneutics', 'Documentation', 'Methodology'],
		principleMatches: [
			'rams-principle-10', // As little design as possible
			'rams-principle-4', // Understandable
			'rams-principle-8' // Thorough - down to last detail
		]
	},
	{
		slug: 'agentic-visualization',
		domain: 'io',
		title: 'Agentic Visualization',
		tags: ['Visualization', 'Tufte', 'Agentic Design'],
		principleMatches: [
			'rams-principle-3', // Aesthetic - visual harmony through restraint
			'rams-principle-6', // Honest - no false promises
			'rams-principle-2' // Useful
		]
	},
	{
		slug: 'data-patterns',
		domain: 'io',
		title: 'Data Patterns',
		tags: ['Visualization', 'Data Analysis', 'Patterns'],
		principleMatches: [
			'rams-principle-2', // Useful
			'rams-principle-4' // Understandable
		]
	}
];

// Principle descriptions for reference comments
const PRINCIPLE_DESCRIPTIONS: Record<string, string> = {
	'rams-principle-1': 'Innovative - don\'t copy, interpret',
	'rams-principle-2': 'Useful - every element serves purpose',
	'rams-principle-3': 'Aesthetic - visual harmony through restraint',
	'rams-principle-4': 'Understandable - self-evident interfaces',
	'rams-principle-5': 'Unobtrusive - tools recede to background',
	'rams-principle-6': 'Honest - no false promises',
	'rams-principle-7': 'Long-lasting - avoid trends',
	'rams-principle-8': 'Thorough - down to last detail',
	'rams-principle-9': 'Environmentally friendly - performance is sustainability',
	'rams-principle-10': 'As little as possible - remove until it breaks'
};

function generateId(): string {
	return 'ref-' + Math.random().toString(36).substring(2, 10);
}

function generateSQL(): string {
	const statements: string[] = [
		'-- Canon References Seed',
		'-- Generated by seed-canon-references.ts',
		`-- Generated at: ${new Date().toISOString()}`,
		'',
		'-- Clear existing references (optional - comment out to preserve)',
		'-- DELETE FROM canon_references;',
		''
	];

	for (const exp of EXPERIMENT_REFERENCES) {
		statements.push(`-- ${exp.title} (${exp.domain}/${exp.slug})`);

		for (const principleId of exp.principleMatches) {
			const description = PRINCIPLE_DESCRIPTIONS[principleId] || principleId;
			const id = generateId();

			statements.push(`INSERT INTO canon_references (id, principle_id, reference_type, reference_slug, reference_domain, description) VALUES (
  '${id}',
  '${principleId}',
  'experiment',
  '${exp.slug}',
  '${exp.domain}',
  'Applies: ${description}'
);`);
		}
		statements.push('');
	}

	statements.push('-- Summary:');
	statements.push(`-- Total references created: ${EXPERIMENT_REFERENCES.reduce((sum, exp) => sum + exp.principleMatches.length, 0)}`);
	statements.push(`-- Experiments linked: ${EXPERIMENT_REFERENCES.length}`);
	statements.push('');

	return statements.join('\n');
}

// Generate and output the SQL
console.log(generateSQL());

// Also output a summary to stderr
console.error('\n=== Canon References Seed ===');
console.error(`Experiments: ${EXPERIMENT_REFERENCES.length}`);
console.error(`References: ${EXPERIMENT_REFERENCES.reduce((sum, exp) => sum + exp.principleMatches.length, 0)}`);
console.error('\nTo apply:');
console.error('  1. Save output to seed.sql: pnpm --filter @create-something/ltd exec tsx scripts/seed-canon-references.ts > seed.sql');
console.error('  2. Execute via wrangler: wrangler d1 execute create-something-db --remote --file=seed.sql');
