/**
 * Generate D1 upsert SQL for agency identity seed rows from a CSV file.
 *
 * Usage:
 *   pnpm exec tsx packages/agency/scripts/prepare-agency-identity-seed.ts docs/examples/agency-user-seed.csv
 */

import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

type SeedRow = Record<string, string>;

const filePath = process.argv[2];
if (!filePath) {
	console.error('Usage: pnpm exec tsx packages/agency/scripts/prepare-agency-identity-seed.ts <csv-file>');
	process.exit(1);
}

const source = readFileSync(resolve(filePath), 'utf8').trim();
if (!source) {
	console.error('Seed CSV is empty.');
	process.exit(1);
}

const [headerLine, ...dataLines] = source.split(/\r?\n/).filter(Boolean);
const headers = parseCsvLine(headerLine).map((value) => value.trim());
const rows = dataLines.map((line) => {
	const values = parseCsvLine(line);
	return headers.reduce<SeedRow>((record, header, index) => {
		record[header] = values[index] ?? '';
		return record;
	}, {});
});

console.log('-- agency identity seed upserts');
console.log('-- generated by prepare-agency-identity-seed.ts');
console.log(rows.map((row, index) => buildUpsert(row, index + 1)).join('\n\n'));

function buildUpsert(row: SeedRow, index: number): string {
	const email = normalizeEmail(row.auth_email);
	if (!email) {
		throw new Error(`Row ${index}: auth_email is required`);
	}
	if (!row.account_id?.trim()) {
		throw new Error(`Row ${index}: account_id is required`);
	}
	if (!row.tenant_id?.trim()) {
		throw new Error(`Row ${index}: tenant_id is required`);
	}

	const metadata = row.metadata_json?.trim() || '{}';
	JSON.parse(metadata);

	return `INSERT INTO agency_identity_seeds (
  normalized_email,
  account_id,
  tenant_id,
  workspace_account_id,
  service_tier,
  managed_bearer_allowed,
  org_membership_active,
  service_entitled,
  policy_accepted,
  contract_active,
  billing_active,
  status,
  invited_at,
  metadata_json
) VALUES (
  ${sql(email)},
  ${sql(row.account_id.trim())},
  ${sql(row.tenant_id.trim())},
  ${sql((row.workspace_account_id || row.account_id).trim())},
  ${sql((row.service_tier || 'agency').trim())},
  ${flag(row.managed_bearer_allowed, true)},
  ${flag(row.org_membership_active, true)},
  ${flag(row.service_entitled, true)},
  ${flag(row.policy_accepted, false)},
  ${flag(row.contract_active, true)},
  ${flag(row.billing_active, true)},
  ${sql((row.status || 'seeded').trim())},
  ${nullable(row.invited_at?.trim())},
  ${sql(metadata)}
) ON CONFLICT(normalized_email) DO UPDATE SET
  account_id = excluded.account_id,
  tenant_id = excluded.tenant_id,
  workspace_account_id = excluded.workspace_account_id,
  service_tier = excluded.service_tier,
  managed_bearer_allowed = excluded.managed_bearer_allowed,
  org_membership_active = excluded.org_membership_active,
  service_entitled = excluded.service_entitled,
  policy_accepted = excluded.policy_accepted,
  contract_active = excluded.contract_active,
  billing_active = excluded.billing_active,
  status = excluded.status,
  invited_at = COALESCE(excluded.invited_at, agency_identity_seeds.invited_at),
  metadata_json = excluded.metadata_json,
  updated_at = datetime('now');`;
}

function parseCsvLine(line: string): string[] {
	const values: string[] = [];
	let current = '';
	let quoted = false;

	for (let index = 0; index < line.length; index += 1) {
		const char = line[index];
		if (char === '"') {
			if (quoted && line[index + 1] === '"') {
				current += '"';
				index += 1;
			} else {
				quoted = !quoted;
			}
			continue;
		}

		if (char === ',' && !quoted) {
			values.push(current);
			current = '';
			continue;
		}

		current += char;
	}

	values.push(current);
	return values;
}

function normalizeEmail(value: string | undefined): string {
	return value?.trim().toLowerCase() ?? '';
}

function flag(value: string | undefined, fallback: boolean): number {
	if (!value?.trim()) return fallback ? 1 : 0;
	return ['1', 'true', 'yes', 'y'].includes(value.trim().toLowerCase()) ? 1 : 0;
}

function sql(value: string): string {
	return `'${value.replace(/'/g, "''")}'`;
}

function nullable(value: string | undefined): string {
	return value ? sql(value) : 'NULL';
}
