[env:m5stack-stopwatch]
platform = espressif32 @ 6.12.0
board = esp32s3box
framework = arduino
monitor_speed = 115200
upload_speed = 460800
board_build.partitions = default_16MB.csv
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.arduino.memory_type = qio_opi
lib_deps =
  https://github.com/m5stack/M5Unified.git#0.2.19
  https://github.com/m5stack/M5GFX.git#0.2.26
  https://github.com/m5stack/M5PM1.git#be9a5456c007c333e7ac963f33bfde1ffa5d82ee
  https://github.com/m5stack/M5IOE1.git#846eec7d05e25c09013be2acdb8804487f48a62e
  bblanchon/ArduinoJson@^7.4.2
build_flags =
  -DCORE_DEBUG_LEVEL=0
  -DESP32S3
  -DBOARD_HAS_PSRAM
  -DARDUINO_USB_CDC_ON_BOOT=1
  -DARDUINO_USB_MODE=1
