/**
 * Session Management Tools — get_session_status, upload_session_context
 * Three-Tier Framework: Automation tier (MCP Tools)
 *
 * Manages the Steel.dev browser session context (Zoom cookies).
 * Sessions expire every 1-2 weeks and need manual refresh via
 * the watch-session.ts script.
 */

import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';

import { SteelClient } from '../lib/steel.js';
import type { SteelSessionContext } from '../lib/steel.js';
import type { D1Database } from '../lib/db.js';
import { getSessionState, setSessionState } from '../lib/db.js';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface SessionToolDeps {
  steelApiKey: string;
  getDb: () => D1Database;
  getSessionContext: () => Promise<SteelSessionContext | null>;
  setSessionContext: (context: SteelSessionContext) => Promise<void>;
}

// ---------------------------------------------------------------------------
// Registration
// ---------------------------------------------------------------------------

export function registerSessionTools(
  server: McpServer,
  deps: SessionToolDeps,
): void {
  // --- get_session_status ---------------------------------------------------
  server.tool(
    'get_session_status',
    {},
    async () => {
      try {
        const db = deps.getDb();

        // Check stored session validity
        const validState = await getSessionState(db, 'session_valid');
        const lastCheckState = await getSessionState(db, 'last_session_check');

        // Check if session context exists
        const sessionContext = await deps.getSessionContext();
        const hasContext = sessionContext !== null;
        const cookieCount = sessionContext?.cookies?.length ?? 0;

        // Try a quick validation with Steel
        let liveCheck: { valid: boolean; error?: string } | null = null;

        if (hasContext) {
          try {
            const steel = new SteelClient(deps.steelApiKey);
            const session = await steel.createSession({
              timeout: 2 * 60 * 1000, // 2 minute session just for checking
              sessionContext: sessionContext!,
            });

            // We successfully created a session — cookies are at least parseable
            await steel.releaseSession(session.id);
            liveCheck = { valid: true };

            await setSessionState(db, 'session_valid', 'true');
            await setSessionState(db, 'last_session_check', new Date().toISOString());
          } catch (e) {
            liveCheck = { valid: false, error: String(e) };
            await setSessionState(db, 'session_valid', 'false');
          }
        }

        return {
          content: [{
            type: 'text',
            text: JSON.stringify({
              has_context: hasContext,
              cookie_count: cookieCount,
              last_known_valid: validState?.value === 'true',
              last_validity_check: validState?.updated_at ?? null,
              last_session_check: lastCheckState?.value ?? null,
              live_check: liveCheck,
              instructions: !hasContext
                ? 'No session context found. Run `npx tsx watch-session.ts` locally to capture Zoom cookies, then use upload_session_context to upload them.'
                : validState?.value === 'false'
                  ? 'Session appears expired. Run `npx tsx watch-session.ts` locally, log into Zoom, then use upload_session_context to upload fresh cookies.'
                  : 'Session context is available.',
            }, null, 2),
          }],
        };
      } catch (e) {
        return {
          content: [{
            type: 'text',
            text: JSON.stringify({ error: String(e) }),
          }],
        };
      }
    },
  );

  // --- upload_session_context -----------------------------------------------
  server.tool(
    'upload_session_context',
    {
      session_context_json: z
        .string()
        .describe(
          'JSON string of the session context object (with cookies array). ' +
          'Generated by running `npx tsx watch-session.ts` and reading the output file.',
        ),
    },
    async ({ session_context_json }) => {
      try {
        // Parse and validate
        let context: SteelSessionContext;
        try {
          context = JSON.parse(session_context_json);
        } catch {
          return {
            content: [{
              type: 'text',
              text: JSON.stringify({ error: 'Invalid JSON. Provide a valid session context object.' }),
            }],
          };
        }

        if (!context.cookies || !Array.isArray(context.cookies)) {
          return {
            content: [{
              type: 'text',
              text: JSON.stringify({
                error: 'Invalid session context: missing "cookies" array.',
              }),
            }],
          };
        }

        // Store the context
        await deps.setSessionContext(context);

        // Update session state in D1
        const db = deps.getDb();
        await setSessionState(db, 'session_valid', 'unknown');
        await setSessionState(db, 'context_uploaded_at', new Date().toISOString());

        return {
          content: [{
            type: 'text',
            text: JSON.stringify({
              success: true,
              cookie_count: context.cookies.length,
              message: 'Session context uploaded. Run sync_clips or get_session_status to verify.',
            }, null, 2),
          }],
        };
      } catch (e) {
        return {
          content: [{
            type: 'text',
            text: JSON.stringify({ error: String(e) }),
          }],
        };
      }
    },
  );
}
