[package]
name = "create_something_client_workspace_desktop"
version = "0.2.0"
edition = "2021"

[lib]
name = "create_something_client_workspace_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
libc = "0.2"
serde_json = "1"
tauri = { version = "2", features = [] }
tauri-plugin-single-instance = "2"
