/**
 * Canon-owned Performance foundation for standalone HTML documents.
 *
 * This deliberately stops at fonts, tokens, and role typography. Product
 * surfaces keep their application layout and behavior local while sharing the
 * same visual authority as Svelte consumers.
 */
export const PERFORMANCE_DOCUMENT_STYLE_VERSION = '1.1.0' as const;

export const performanceDocumentFontLinks = ``;

export const performanceDocumentCss = `:root{color-scheme:light;--color-performance-paper:#f3f3f0;--color-performance-panel:#fff;--color-performance-ink:#090909;--color-performance-ink-soft:#262626;--color-performance-muted:#5e6268;--color-performance-line:#d7d7d2;--color-performance-line-strong:#9c9c96;--color-performance-grid:rgb(9 9 9 / .055);--color-performance-growth:#007a4d;--color-performance-growth-soft:#dcece5;--color-performance-signal:#0057b8;--color-performance-signal-soft:#dce8f5;--color-performance-pressure:#e54800;--color-performance-pressure-soft:#f7e2d7;--color-performance-risk:#c62026;--color-performance-risk-soft:#f3dadd;--color-performance-gold:#8b6b00;--color-performance-gold-soft:#eee6cc;--color-performance-controlled:var(--color-performance-signal);--color-performance-controlled-soft:var(--color-performance-signal-soft);--color-performance-ready:var(--color-performance-growth);--color-performance-ready-soft:var(--color-performance-growth-soft);--color-performance-review:var(--color-performance-gold);--color-performance-review-soft:var(--color-performance-gold-soft);--color-performance-stop:var(--color-performance-risk);--color-performance-stop-soft:var(--color-performance-risk-soft);--shadow-performance-panel:none;--shadow-performance-node:none;--radius-performance-sm:0;--radius-performance-md:4px;--content-width-performance:85rem;--font-performance-sans:Arial,"Helvetica Neue",Helvetica,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;--font-performance-display:var(--font-performance-sans);--font-performance-mono:"SFMono-Regular","SF Mono",Menlo,Monaco,Consolas,monospace;--font-performance-display-weight:500;--tracking-performance-display:-.03em;--leading-performance-display:.94;--font-sans:var(--font-performance-display);--font-display:var(--font-performance-display);--font-heading:var(--font-performance-display);--font-interface:var(--font-performance-display);--font-prose:var(--font-performance-display);--font-mono:var(--font-performance-mono);--font-record:var(--font-performance-mono);--font-topology-label:var(--font-performance-mono);--font-code:var(--font-performance-mono)}:where(html){background:var(--color-performance-paper);color:var(--color-performance-ink)}:where(body){font-family:var(--font-performance-display);font-kerning:normal;font-feature-settings:"kern" 1,"liga" 1}:where(h1,h2,h3){font-family:var(--font-performance-display);font-weight:var(--font-performance-display-weight);letter-spacing:var(--tracking-performance-display);line-height:var(--leading-performance-display)}:where([data-performance-role="label"],[data-performance-role="record"],code,kbd,samp){font-family:var(--font-performance-mono);font-variant-numeric:tabular-nums}`;
