// Static subcategory data - bundled with the application
export const subcategoryData = {
  "all_subcategories": [
    "A/B Testing",
    "AI",
    "API Integration",
    "Accounting Integration",
    "Advocacy & Campaigns",
    "Agriculture",
    "Analytics",
    "Appointment Booking",
    "Architecture",
    "Art & Design Blog",
    "Arts & Crafts Store",
    "Asset Management",
    "Audio & Podcast Tools",
    "Automation",
    "Bakery",
    "Banking & Investment",
    "Bar & Nightclub",
    "Beauty & Wellness Store",
    "Blockchain, Cryptocurrency & NFTs",
    "Book",
    "Books & Publishers Store",
    "Business & Finance Blog",
    "CMS Integration",
    "CRM Integration",
    "Cafe & Coffee Shop",
    "Cars",
    "Catering & Delivery",
    "Charity & Fundraising",
    "Chiropractor & Physiotherapist",
    "Classes & Courses",
    "Cleaning",
    "Clinic & Pharmacy",
    "Code Editing",
    "Collaboration Tools",
    "College / University",
    "Color & Typography",
    "Coming Soon",
    "Comment Systems",
    "Compliance",
    "Consulting & Coaching",
    "Contact Forms",
    "Content Generation",
    "Content Management",
    "Content Scheduling & Automation",
    "Creative Agency",
    "Creators & Influencers",
    "Customer Support",
    "Dance",
    "Data Sync",
    "Dentist",
    "Design",
    "Design Portfolio",
    "Developer Tools",
    "Development and Coding",
    "Digital Products Store",
    "Doctor",
    "Documentation",
    "E-Learning",
    "Early Education",
    "Ecommerce",
    "Electronics Store",
    "Email Marketing",
    "Environment",
    "Event Production",
    "Events",
    "Events, Conferences & Meetups",
    "Fashion & Clothing Store",
    "Feedback Collection",
    "File Management",
    "Film & TV",
    "Finance & Accounting",
    "Fitness & Gym",
    "Florist & Plants Store",
    "Food & Drinks Store",
    "Food & Recipe Blog",
    "Forms and Surveys",
    "Forums & Discussion Boards",
    "Foundation & NGO",
    "Foundations & NGO",
    "Freelancers & Consultants",
    "Gallery & Museum",
    "Gaming",
    "Health & Nutrition",
    "Health & Wellness",
    "Help Desk Integration",
    "Home Construction",
    "Home Decor Store",
    "Home Services & Maintenance",
    "Hospital",
    "Hotels & Lodging",
    "IT Company",
    "Icons",
    "Image Effects",
    "Image and Video Display Tools",
    "Insurance",
    "Interior Design",
    "Invoicing & Billing",
    "Jewelry & Accessories Store",
    "Job Portal",
    "Kids & Babies Store",
    "Landscaping & Gardening",
    "Law Firm & Attorney",
    "Lead Generation",
    "Lifestyle Blog",
    "Live Chat",
    "Localization",
    "Magazine",
    "Makeup & Cosmetics",
    "Maps",
    "Marketing",
    "Marketing & Advertising",
    "Mobile App",
    "Music Events & Festivals",
    "Music Industry & Promotion",
    "Musicians & Bands",
    "Nature & Conservation",
    "News",
    "Newsletter",
    "Online Education",
    "Order Management",
    "Outdoor & Adventure",
    "Payment Processing",
    "Personal Blog",
    "Pets & Animals Store",
    "Photography & Video Portfolio",
    "Podcast & Radio",
    "Political",
    "Polls and Quizzes",
    "Product Display and Catalogues",
    "Project Management Integration",
    "Property Management & HOA",
    "Public services",
    "Real Estate",
    "Recruiting",
    "Religious & Spiritual",
    "Renewable energy",
    "Residential Design",
    "Restaurant",
    "Resume & CV",
    "Retail & E-Commerce",
    "SEO",
    "SEO Analytics",
    "SEO Tools",
    "Salon & Barbershop",
    "Scheduling",
    "Schools",
    "Shipping and Delivery",
    "Shopping Cart",
    "Site Elements & Widgets",
    "Social Media Integrations",
    "Social Media Marketing",
    "Software & SaaS",
    "Spa",
    "Sports",
    "Sports & Outdoors Store",
    "Startup",
    "Support/Help center",
    "Survey Tools",
    "Sustainability",
    "Task Automation",
    "Tattoo",
    "Testing & Debugging",
    "Text Editing",
    "Themes & Templates",
    "Therapy & Psychology",
    "Time Tracking",
    "Transportation & Logistics",
    "Travel & Tourism",
    "Travel Blog",
    "UI Kit",
    "UX Tools",
    "User Management",
    "User Reviews & Ratings",
    "User/Member System",
    "Utilities",
    "Veterinary",
    "Volunteer & Community",
    "Waitlist",
    "Website Translation",
    "Weddings",
    "Winery"
  ]
};
