
const colorTokens = {
  'bg-pure': 'var(--color-bg-pure)',
  'bg-elevated': 'var(--color-bg-elevated)',
  'bg-surface': 'var(--color-bg-surface)',
  'bg-subtle': 'var(--color-bg-subtle)',
  'fg-primary': 'var(--color-fg-primary)',
  'fg-secondary': 'var(--color-fg-secondary)',
  'fg-tertiary': 'var(--color-fg-tertiary)',
  'fg-muted': 'var(--color-fg-muted)',
  'fg-subtle': 'var(--color-fg-subtle)',
  'border-default': 'var(--color-border-default)',
  'border-emphasis': 'var(--color-border-emphasis)',
  'border-strong': 'var(--color-border-strong)',
  success: 'var(--color-success)',
  'success-muted': 'var(--color-success-muted)',
  'success-border': 'var(--color-success-border)',
  error: 'var(--color-error)',
  'error-muted': 'var(--color-error-muted)',
  'error-border': 'var(--color-error-border)',
  warning: 'var(--color-warning)',
  'warning-muted': 'var(--color-warning-muted)',
  'warning-border': 'var(--color-warning-border)',
  info: 'var(--color-info)',
  'info-muted': 'var(--color-info-muted)',
  'info-border': 'var(--color-info-border)',
  hover: 'var(--color-hover)',
  active: 'var(--color-active)',
  focus: 'var(--color-focus)',
  overlay: 'var(--color-overlay)',
  'overlay-heavy': 'var(--color-overlay-heavy)',
  'data-1': 'var(--color-data-1)',
  'data-1-muted': 'var(--color-data-1-muted)',
  'data-2': 'var(--color-data-2)',
  'data-2-muted': 'var(--color-data-2-muted)',
  'data-3': 'var(--color-data-3)',
  'data-3-muted': 'var(--color-data-3-muted)',
  'data-3-border': 'var(--color-data-3-border)',
  'data-4': '.var(--color-data-4)',
  'data-4-muted': 'var(--color-data-4-muted)',
  'data-5': 'var(--color-data-5)',
  'data-5-muted': 'var(--color-data-5-muted)',
  'data-6': 'var(--color-data-6)',
  'data-6-muted': 'var(--color-data-6-muted)',
  'rank-gold': 'var(--color-rank-gold)',
  'rank-gold-muted': 'var(--color-rank-gold-muted)',
  'rank-bronze': 'var(--color-rank-bronze)',
  'rank-bronze-muted': 'var(--color-rank-bronze-muted)',
};

export default colorTokens;
