#!/bin/bash

set -euo pipefail

INFISICAL_PROJECT_ID="${INFISICAL_PROJECT_ID:-}"
INFISICAL_ENV="${INFISICAL_ENV:-prod}"
INFISICAL_PATH="${INFISICAL_PATH:-/}"
INFISICAL_INCLUDE_IMPORTS="${INFISICAL_INCLUDE_IMPORTS:-true}"
OUTPUT_FILE="${OUTPUT_FILE:-$HOME/.config/create-something/infisical-shell-secrets.zsh}"

SECRET_NAMES=(
  LINEAR_API_KEY
  VULTR_API_KEY
  AIRTABLE_BASE_ID
  AIRTABLE_API_TOKEN
  AIRTABLE_TABLE_ID
  N8N_OPENAI_API_KEY
  RAGIE_API_KEY
  OPENAI_API_KEY
  PERPLEXITY_API_KEY
  NOTION_SYNC_BEARER_TOKEN
  SLACK_CREATE_SOMETHING_MCP_TOKEN
)

usage() {
  cat <<'EOF'
Usage:
  bash scripts/shell-secrets-sync.sh

Environment:
  INFISICAL_PROJECT_ID        Optional Infisical project ID
  INFISICAL_ENV               Infisical environment slug (default: prod)
  INFISICAL_PATH              Infisical path/folder (default: /)
  INFISICAL_INCLUDE_IMPORTS   Whether to include imported secrets (default: true)
  OUTPUT_FILE                 Output shell file (default: ~/.config/create-something/infisical-shell-secrets.zsh)
EOF
}

require_cmd() {
  if ! command -v "$1" >/dev/null 2>&1; then
    echo "missing required command: $1" >&2
    exit 1
  fi
}

main() {
  if [[ "${1:-}" == "--help" || "${1:-}" == "-h" ]]; then
    usage
    exit 0
  fi

  require_cmd infisical

  mkdir -p "$(dirname "$OUTPUT_FILE")"

  local tmp_env
  tmp_env="$(mktemp)"

  local -a export_cmd=(
    infisical export
    --format=dotenv
    --env="$INFISICAL_ENV"
    --path="$INFISICAL_PATH"
    --include-imports="$INFISICAL_INCLUDE_IMPORTS"
  )

  if [[ -n "$INFISICAL_PROJECT_ID" ]]; then
    export_cmd+=(--projectId="$INFISICAL_PROJECT_ID")
  fi

  "${export_cmd[@]}" >"$tmp_env"

  (
    set -a
    # shellcheck disable=SC1090
    source "$tmp_env"
    set +a

    {
      echo "# Generated by scripts/shell-secrets-sync.sh"
      echo "# Source: Infisical env=$INFISICAL_ENV path=$INFISICAL_PATH"
      for name in "${SECRET_NAMES[@]}"; do
        if [[ -n "${!name:-}" ]]; then
          printf 'export %s=%q\n' "$name" "${!name}"
        fi
      done
    } >"$OUTPUT_FILE"
  )

  chmod 600 "$OUTPUT_FILE"
  rm -f "$tmp_env"
  echo "wrote shell secrets cache to $OUTPUT_FILE"
}

main "$@"
