export const policyEnv = {
  AGENTIC_MAX_TASK_USD: '2', AGENTIC_LIFETIME_BUDGET_USD: '4',
  AGENTIC_LIFETIME_TASK_LIMIT: '3', AGENTIC_CALL_RESERVATION_USD: '0.5',
  AGENTIC_INPUT_USD_PER_MILLION:'3', AGENTIC_OUTPUT_USD_PER_MILLION:'15', AGENTIC_MAX_REQUEST_BYTES: '50000', AGENTIC_SESSION_TIMEOUT_MS: '60000'
};
