name = "cato-supply-insights-cms"
main = "src/worker.mjs"
compatibility_date = "2026-07-06"
account_id = "9645bd52e640b8a4f40a3a55ff1dd75a"

[vars]
WEBFLOW_SITE_ID = "69241b6e09c89ae05c6116f8"
WEBFLOW_INSIGHTS_COLLECTION_ID = "69fd0ee732ea65ee49381665"
WEBFLOW_INSIGHT_CATEGORIES_COLLECTION_ID = "69fd0ee67376b07b7f2de5d0"
WEBFLOW_TEAM_COLLECTION_ID = "69255f78c214e919f388455c"
