#!/usr/bin/env node
// One-time generator for the ECDSA P-256 keypair that signs Core Ink
// firmware manifests. Run once, then:
//
//   1. Upload the printed `INK_FIRMWARE_SIGNING_PRIVATE_JWK` into Infisical.
//   2. Replace `include/firmware_signing_pubkey.h` with the printed header.
//   3. Delete any local copies of the private key.
//
// Public-key rotation requires reflashing every device. Keep the JWK safe.

import { webcrypto } from 'node:crypto';
import { writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');

const kp = await webcrypto.subtle.generateKey(
  { name: 'ECDSA', namedCurve: 'P-256' },
  true,
  ['sign', 'verify'],
);

const privateJwk = await webcrypto.subtle.exportKey('jwk', kp.privateKey);
const publicRaw = new Uint8Array(await webcrypto.subtle.exportKey('raw', kp.publicKey));
if (publicRaw.length !== 65 || publicRaw[0] !== 0x04) {
  throw new Error(`unexpected public key shape (got ${publicRaw.length} bytes, leading 0x${publicRaw[0].toString(16)})`);
}

const hex = Array.from(publicRaw).map((b) => `0x${b.toString(16).padStart(2, '0')}`);
const rows = [];
for (let i = 0; i < hex.length; i += 8) rows.push('  ' + hex.slice(i, i + 8).join(', '));

const header = `// Auto-generated by scripts/sign-keygen.mjs. Do not edit by hand.
// SECP256R1 / P-256 public key, uncompressed point (0x04 || X || Y).
//
// Rotating this key requires reflashing every device. Keep the matching
// private JWK in Infisical as INK_FIRMWARE_SIGNING_PRIVATE_JWK.

#pragma once

#include <stdint.h>

static constexpr uint8_t INK_FIRMWARE_SIGNING_PUBKEY[65] = {
${rows.join(',\n')}
};
`;

const headerPath = resolve(root, 'include/firmware_signing_pubkey.h');
await mkdir(dirname(headerPath), { recursive: true });
await writeFile(headerPath, header);

// Drop the private JWK to a 0600 file the operator can hand-carry into
// Infisical and then delete. Never log it to stdout to keep it out of shell
// scrollback.
const privatePath = resolve(root, 'tmp/ink-signing-private.jwk.json');
await mkdir(dirname(privatePath), { recursive: true });
await writeFile(privatePath, JSON.stringify(privateJwk, null, 2), { mode: 0o600 });

console.log(`Wrote public key header   -> ${headerPath}`);
console.log(`Wrote private JWK (0600)  -> ${privatePath}`);
console.log('');
console.log('Next steps:');
console.log('  1. Open the JWK file above, copy its contents.');
console.log('  2. Upload to Infisical as INK_FIRMWARE_SIGNING_PRIVATE_JWK.');
console.log('  3. Delete the local file:  rm ' + privatePath);
console.log('  4. Commit the public-key header.');
console.log('  5. Rebuild and reflash firmware so the new public key is on-device.');
