import type { LoomFormula } from './runtime-routing.js';

const FORMULAS: LoomFormula[] = [
  {
    name: 'basic-task',
    description: 'Simple, mechanical task with clear scope',
    quality: 'basic',
    agent: 'gemini',
    variables: [
      {
        name: 'task_id',
        description: 'The task ID to work on',
        required: true,
        default: null,
      },
    ],
    steps: [
      {
        id: 'understand',
        title: 'Understand the task',
        description: 'Read task description and acceptance criteria',
        agent: null,
        labels: [],
        prompt: null,
        verify: null,
        checkpoint: false,
        parallel: false,
      },
      {
        id: 'execute',
        title: 'Execute the work',
        description: 'Complete the task according to specifications',
        agent: null,
        labels: [],
        prompt: null,
        verify: null,
        checkpoint: true,
        parallel: false,
      },
      {
        id: 'verify',
        title: 'Quick verification',
        description: 'Basic sanity check',
        agent: null,
        labels: [],
        prompt: null,
        verify: 'pnpm check',
        checkpoint: false,
        parallel: false,
      },
    ],
    success_criteria: {
      criteria: ['All steps completed without errors', 'Task updated with completion status'],
      verify_commands: ['pnpm check'],
      ground_checks: [],
    },
    labels: ['basic'],
    estimated_tokens: 5000,
  },
  {
    name: 'feature',
    description: 'Implement a new feature with planning and testing',
    quality: 'standard',
    agent: 'codex',
    variables: [
      {
        name: 'feature_name',
        description: 'Name of the feature',
        required: true,
        default: null,
      },
      {
        name: 'package',
        description: 'Package to implement in',
        required: true,
        default: null,
      },
    ],
    steps: [
      {
        id: 'plan',
        title: 'Plan the implementation',
        description: 'Analyze requirements, identify files to modify, plan approach',
        agent: 'codex',
        labels: ['planning'],
        prompt: 'Plan the implementation of {{feature_name}} in {{package}}. Identify files to modify and approach.',
        verify: null,
        checkpoint: true,
        parallel: false,
      },
      {
        id: 'implement',
        title: 'Implement the feature',
        description: 'Write the code following the plan',
        agent: null,
        labels: ['coding'],
        prompt: null,
        verify: 'pnpm check',
        checkpoint: true,
        parallel: false,
      },
      {
        id: 'test',
        title: 'Write tests',
        description: 'Add tests for the new functionality',
        agent: null,
        labels: ['testing'],
        prompt: null,
        verify: 'pnpm test',
        checkpoint: true,
        parallel: false,
      },
      {
        id: 'review',
        title: 'Self-review',
        description: 'Review changes for quality, DRY violations, and repo standards',
        agent: 'codex',
        labels: ['review'],
        prompt: null,
        verify: null,
        checkpoint: false,
        parallel: false,
      },
    ],
    success_criteria: {
      criteria: ['Feature works as specified', 'Tests pass', 'No TypeScript errors', 'No standards violations'],
      verify_commands: ['pnpm check', 'pnpm test', 'pnpm lint'],
      ground_checks: [],
    },
    labels: ['feature'],
    estimated_tokens: 30000,
  },
  {
    name: 'bug-fix',
    description: 'Diagnose and fix a bug',
    quality: 'standard',
    agent: 'codex',
    variables: [
      {
        name: 'bug_description',
        description: 'Description of the bug',
        required: true,
        default: null,
      },
    ],
    steps: [
      {
        id: 'reproduce',
        title: 'Reproduce the bug',
        description: 'Understand and reproduce the bug',
        agent: null,
        labels: ['debugging'],
        prompt: 'Analyze and reproduce: {{bug_description}}',
        verify: null,
        checkpoint: true,
        parallel: false,
      },
      {
        id: 'diagnose',
        title: 'Diagnose root cause',
        description: 'Find the root cause of the bug',
        agent: 'codex',
        labels: ['debugging'],
        prompt: null,
        verify: null,
        checkpoint: true,
        parallel: false,
      },
      {
        id: 'fix',
        title: 'Implement fix',
        description: 'Fix the bug',
        agent: null,
        labels: ['coding'],
        prompt: null,
        verify: 'pnpm check',
        checkpoint: true,
        parallel: false,
      },
      {
        id: 'verify',
        title: 'Verify fix',
        description: 'Verify the bug is fixed and no regressions',
        agent: null,
        labels: ['testing'],
        prompt: null,
        verify: 'pnpm test',
        checkpoint: false,
        parallel: false,
      },
    ],
    success_criteria: {
      criteria: ['Bug is fixed', 'No regressions', 'Tests pass'],
      verify_commands: ['pnpm check', 'pnpm test'],
      ground_checks: [],
    },
    labels: ['bug', 'fix'],
    estimated_tokens: 20000,
  },
  {
    name: 'refactor',
    description: 'Refactor code with DRY verification',
    quality: 'premium',
    agent: 'codex',
    variables: [
      {
        name: 'target',
        description: 'File or directory to refactor',
        required: true,
        default: null,
      },
      {
        name: 'goal',
        description: 'What to improve',
        required: true,
        default: null,
      },
    ],
    steps: [
      {
        id: 'analyze',
        title: 'Analyze current state',
        description: 'Use Ground to find issues',
        agent: null,
        labels: ['refactor'],
        prompt: 'Analyze {{target}} for: {{goal}}',
        verify: null,
        checkpoint: true,
        parallel: false,
      },
      {
        id: 'plan',
        title: 'Plan refactoring',
        description: 'Create safe refactoring plan',
        agent: 'codex',
        labels: ['planning'],
        prompt: null,
        verify: null,
        checkpoint: true,
        parallel: false,
      },
      {
        id: 'refactor',
        title: 'Apply refactoring',
        description: 'Make the changes',
        agent: null,
        labels: ['refactor'],
        prompt: null,
        verify: 'pnpm check',
        checkpoint: true,
        parallel: false,
      },
      {
        id: 'verify-ground',
        title: 'Verify with Ground',
        description: 'Run Ground to verify improvements',
        agent: null,
        labels: ['verify'],
        prompt: null,
        verify: 'ground find duplicates {{target}}',
        checkpoint: false,
        parallel: false,
      },
    ],
    success_criteria: {
      criteria: ['Refactoring goal achieved', 'No regressions', 'Ground shows improvement'],
      verify_commands: ['pnpm check', 'pnpm test'],
      ground_checks: ['find duplicates', 'find dead-code'],
    },
    labels: ['refactor', 'dry'],
    estimated_tokens: 25000,
  },
  {
    name: 'cs-feature',
    description: 'Create Something feature implementation with Canon compliance',
    quality: 'premium',
    agent: 'codex',
    variables: [
      {
        name: 'feature_name',
        description: 'Name of the feature',
        required: true,
        default: null,
      },
      {
        name: 'package',
        description: 'Package to implement in (io, agency, tend, etc.)',
        required: true,
        default: null,
      },
    ],
    steps: [
      {
        id: 'verify-exports',
        title: 'Verify component availability',
        description: "Use 'pnpm exports' to verify imports exist before using them",
        agent: null,
        labels: ['planning'],
        prompt: "Before implementing {{feature_name}}, verify all imports using 'pnpm exports {{package}}'",
        verify: 'pnpm exports {{package}}',
        checkpoint: true,
        parallel: false,
      },
      {
        id: 'plan',
        title: 'Plan implementation',
        description: 'Design the feature following Canon standards',
        agent: 'codex',
        labels: ['planning'],
        prompt: null,
        verify: null,
        checkpoint: true,
        parallel: false,
      },
      {
        id: 'implement',
        title: 'Implement feature',
        description: 'Build the feature in {{package}}',
        agent: null,
        labels: ['coding'],
        prompt: null,
        verify: 'pnpm check',
        checkpoint: true,
        parallel: false,
      },
      {
        id: 'canon-check',
        title: 'Canon compliance check',
        description: 'Verify adherence to Canon standards',
        agent: null,
        labels: ['canon'],
        prompt: null,
        verify: 'pnpm lint',
        checkpoint: false,
        parallel: false,
      },
      {
        id: 'ground-verify',
        title: 'Ground verification',
        description: 'Run Ground to verify no DRY violations',
        agent: null,
        labels: ['ground'],
        prompt: null,
        verify: 'ground analyze packages/{{package}}/src',
        checkpoint: false,
        parallel: false,
      },
    ],
    success_criteria: {
      criteria: ['Feature works as specified', 'Canon compliant (no linter errors)', 'Ground verification passed', 'No hallucinated imports'],
      verify_commands: ['pnpm check', 'pnpm lint', 'pnpm test'],
      ground_checks: ['duplicates', 'dead_exports'],
    },
    labels: ['feature', 'canon'],
    estimated_tokens: 40000,
  },
  {
    name: 'cs-component',
    description: 'Create a Svelte component following Create Something patterns',
    quality: 'standard',
    agent: 'cursor',
    variables: [
      {
        name: 'component_name',
        description: 'Name of the component (PascalCase)',
        required: true,
        default: null,
      },
      {
        name: 'package',
        description: 'Package (components, io, agency)',
        required: false,
        default: 'components',
      },
    ],
    steps: [
      {
        id: 'check-existing',
        title: 'Check for existing components',
        description: "Verify component doesn't already exist",
        agent: null,
        labels: [],
        prompt: 'Check if {{component_name}} exists in @create-something/{{package}}',
        verify: 'pnpm exports {{package}} {{component_name}}',
        checkpoint: false,
        parallel: false,
      },
      {
        id: 'implement',
        title: 'Create component',
        description: 'Implement the Svelte component',
        agent: 'cursor',
        labels: ['ui', 'svelte'],
        prompt: null,
        verify: 'pnpm check',
        checkpoint: true,
        parallel: false,
      },
      {
        id: 'export',
        title: 'Add to exports',
        description: 'Export from package index',
        agent: null,
        labels: [],
        prompt: null,
        verify: 'pnpm exports {{package}} {{component_name}}',
        checkpoint: false,
        parallel: false,
      },
    ],
    success_criteria: {
      criteria: ['Component renders correctly', 'Exported from package', 'Props typed correctly'],
      verify_commands: ['pnpm check'],
      ground_checks: [],
    },
    labels: ['ui', 'svelte', 'components'],
    estimated_tokens: 15000,
  },
  {
    name: 'cs-refactor',
    description: 'Refactor with Ground verification (DRY, dead code, orphans)',
    quality: 'premium',
    agent: 'codex',
    variables: [
      {
        name: 'target',
        description: 'File or directory to refactor',
        required: true,
        default: null,
      },
      {
        name: 'goal',
        description: 'What to improve (dry, cleanup, organize)',
        required: true,
        default: null,
      },
    ],
    steps: [
      {
        id: 'baseline',
        title: 'Establish baseline',
        description: 'Run Ground to see current issues',
        agent: null,
        labels: ['ground'],
        prompt: 'Run ground analyze on {{target}} to establish baseline',
        verify: null,
        checkpoint: true,
        parallel: false,
      },
      {
        id: 'plan',
        title: 'Plan refactoring',
        description: 'Design safe refactoring approach',
        agent: 'codex',
        labels: ['planning'],
        prompt: null,
        verify: null,
        checkpoint: true,
        parallel: false,
      },
      {
        id: 'refactor',
        title: 'Apply changes',
        description: 'Make the refactoring changes',
        agent: null,
        labels: ['refactor'],
        prompt: null,
        verify: 'pnpm check && pnpm test',
        checkpoint: true,
        parallel: false,
      },
      {
        id: 'verify-improvement',
        title: 'Verify improvement',
        description: 'Run Ground diff to verify improvement',
        agent: null,
        labels: ['ground', 'verify'],
        prompt: null,
        verify: 'ground diff {{target}}',
        checkpoint: false,
        parallel: false,
      },
    ],
    success_criteria: {
      criteria: ['Ground shows improvement', 'No regressions', 'Tests pass'],
      verify_commands: ['pnpm check', 'pnpm test'],
      ground_checks: ['duplicates', 'dead_exports', 'orphans'],
    },
    labels: ['refactor', 'dry', 'ground'],
    estimated_tokens: 30000,
  },
  {
    name: 'cs-worker',
    description: 'Create a Cloudflare Worker with proper environment handling',
    quality: 'premium',
    agent: 'codex',
    variables: [
      {
        name: 'worker_name',
        description: 'Name of the worker',
        required: true,
        default: null,
      },
      {
        name: 'package',
        description: 'Parent package',
        required: false,
        default: 'agency',
      },
    ],
    steps: [
      {
        id: 'scaffold',
        title: 'Scaffold worker',
        description: 'Create worker structure',
        agent: null,
        labels: ['workers'],
        prompt: null,
        verify: null,
        checkpoint: true,
        parallel: false,
      },
      {
        id: 'implement',
        title: 'Implement handler',
        description: 'Write the worker logic',
        agent: 'codex',
        labels: ['workers', 'coding'],
        prompt: null,
        verify: 'pnpm check',
        checkpoint: true,
        parallel: false,
      },
      {
        id: 'env-check',
        title: 'Environment safety check',
        description: 'Verify no Node.js APIs leak into Worker',
        agent: null,
        labels: ['workers', 'ground'],
        prompt: null,
        verify: 'ground check-environment packages/{{package}}/workers/{{worker_name}}/src/index.ts',
        checkpoint: false,
        parallel: false,
      },
    ],
    success_criteria: {
      criteria: ['Worker deploys', 'No environment safety issues', 'Handles edge cases'],
      verify_commands: ['pnpm check'],
      ground_checks: ['environment'],
    },
    labels: ['workers', 'cloudflare'],
    estimated_tokens: 25000,
  },
  {
    name: 'fleet-deploy',
    description: 'Policy-gated MCP hub fleet deployment with post-deploy verification',
    quality: 'premium',
    agent: 'codex',
    variables: [
      {
        name: 'gate_profile',
        description: 'Gate profile (strict or warmup)',
        required: false,
        default: 'strict',
      },
      {
        name: 'rollout_mode',
        description: 'Target rollout mode (shadow or polar_enforce)',
        required: false,
        default: 'shadow',
      },
    ],
    steps: [
      {
        id: 'preflight-gates',
        title: 'Run preflight quality gates',
        description: 'Run typecheck and lint quality gates before deploy',
        agent: null,
        labels: ['quality-gate'],
        prompt: null,
        verify: 'pnpm mcp:gate:typecheck && pnpm mcp:gate:lint',
        checkpoint: true,
        parallel: false,
      },
      {
        id: 'deploy-fleet',
        title: 'Deploy fleet',
        description: 'Deploy all configured fleet workers',
        agent: 'codex',
        labels: ['deploy', 'write-intent'],
        prompt: 'Deploy using gate_profile={{gate_profile}} rollout_mode={{rollout_mode}} and record any policy exceptions.',
        verify: 'pnpm mcp:hub:fleet:deploy',
        checkpoint: true,
        parallel: false,
      },
      {
        id: 'verify-fleet',
        title: 'Verify fleet health',
        description: 'Run protocol and health verification after deploy',
        agent: null,
        labels: ['verification'],
        prompt: null,
        verify: 'pnpm mcp:hub:fleet:verify',
        checkpoint: false,
        parallel: false,
      },
    ],
    success_criteria: {
      criteria: ['All targeted workers deploy successfully', 'Post-deploy verification passes', 'Policy gate outcomes are recorded'],
      verify_commands: ['pnpm mcp:hub:fleet:deploy', 'pnpm mcp:hub:fleet:verify'],
      ground_checks: [],
    },
    labels: ['fleet', 'deploy', 'policy-gated', 'write-intent'],
    estimated_tokens: 30000,
  },
  {
    name: 'fleet-verify',
    description: 'Run fleet verification and collect rollout evidence',
    quality: 'standard',
    agent: 'codex',
    variables: [
      {
        name: 'emit_eval',
        description: 'Run Langfuse eval checks (true or false)',
        required: false,
        default: 'true',
      },
    ],
    steps: [
      {
        id: 'verify-hub-fleet',
        title: 'Run fleet verification',
        description: 'Run MCP protocol and health checks across workers',
        agent: null,
        labels: ['verification', 'read-only'],
        prompt: null,
        verify: 'pnpm mcp:hub:fleet:verify',
        checkpoint: true,
        parallel: false,
      },
      {
        id: 'collect-evidence',
        title: 'Collect eval evidence',
        description: 'Run contract/error-path checks when requested',
        agent: null,
        labels: ['eval'],
        prompt: 'If emit_eval={{emit_eval}} is true, run contract/error-path eval scripts and summarize failures.',
        verify: 'pnpm langfuse:eval:mcp:contract && pnpm langfuse:eval:mcp:error-path',
        checkpoint: false,
        parallel: false,
      },
    ],
    success_criteria: {
      criteria: ['Fleet verification passes', 'Eval evidence captured for reviewers'],
      verify_commands: ['pnpm mcp:hub:fleet:verify'],
      ground_checks: [],
    },
    labels: ['fleet', 'verify', 'read-only'],
    estimated_tokens: 18000,
  },
  {
    name: 'mcp-gate',
    description: 'Run MCP quality gates with scoped stage control',
    quality: 'standard',
    agent: 'codex',
    variables: [
      {
        name: 'stage',
        description: 'Gate stage (all|typecheck|lint|test)',
        required: false,
        default: 'all',
      },
      {
        name: 'scope',
        description: 'Gate scope (active|fleet|all)',
        required: false,
        default: 'active',
      },
    ],
    steps: [
      {
        id: 'run-gate',
        title: 'Run MCP quality gate',
        description: 'Execute stage/scope quality gate command',
        agent: null,
        labels: ['quality-gate'],
        prompt: 'Run MCP quality gate with stage={{stage}} scope={{scope}} and report failing packages only.',
        verify: 'node scripts/mcp-quality-gate.mjs {{stage}} --scope={{scope}}',
        checkpoint: true,
        parallel: false,
      },
    ],
    success_criteria: {
      criteria: ['Selected MCP quality gate passes', 'Failure summary is captured when gate fails'],
      verify_commands: ['node scripts/mcp-quality-gate.mjs {{stage}} --scope={{scope}}'],
      ground_checks: [],
    },
    labels: ['mcp', 'quality-gate'],
    estimated_tokens: 12000,
  },
];

const FORMULA_MAP = new Map(FORMULAS.map((formula) => [formula.name, formula]));

export function listBuiltInFormulas(): LoomFormula[] {
  return [...FORMULAS].sort((a, b) => a.name.localeCompare(b.name));
}

export function getBuiltInFormula(name: string): LoomFormula | null {
  return FORMULA_MAP.get(name) ?? null;
}
